services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - charles_net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - charles_net

networks:
  charles_net:
    driver: bridge
